import keys

GEOLITE_HOST = 'geolite.info'
GEOLITE_API_KEY = keys.MAXMIND_KEY
GEOLITE_USER_ID = keys.MAXMIND_USER_ID

POSTGRES_DB = "astra"
POSTGRES_USER = "astra"
POSTGRES_PASSWORD = keys.POSTGRES_PASSWORD
POSTGRES_URL = "localhost"
POSTGRES_PORT = "5432"