version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_PASSWORD=astra
      - POSTGRES_USER=astra
      - POSTGRES_DB=astra
    ports:
      - "5432:5432"
  web:
    image: astra_test
    container_name: web_server
    depends_on:
      - database
    ports:
      - "8080:8080"
    build: .
